# This is an example file - DO NOT commit actual secrets!
# Use scripts/04-setup-secrets.sh to create actual secrets from config/.env

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
stringData:
  POSTGRES_USER: "n8n_user"
  POSTGRES_PASSWORD: "CHANGE_ME_STRONG_PASSWORD"
  POSTGRES_DB: "n8n"
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "CHANGE_ME_STRONG_PASSWORD"
  N8N_ENCRYPTION_KEY: "CHANGE_ME_32_CHARS_ENCRYPTION_KEY"
